### ISSUE TITLE
Set up immersiveweb.org

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/administrivia#1]
Sub tasks may include:
- Pointing all already registered domain names to immersiveweb.org
- Updating webvr.rocks content for the brave new WebXR world
- Reimburse folks who paid for domains?

**Comment by AdaRoseCannon** [comment]
Todo: Fork https://github.com/immersive-web/webvrrocks update with new copy.

**Comment by LaszloGombos** [comment]
just in case it might be relevant/helpful - damon.h@samsung (dot.com) maintains http://www.createwebvr.com/

**Comment by Yonet** [comment]
We have https://immersiveweb.dev/
