### ISSUE TITLE
Change repo default branches from master to main

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#107]
WG
- [ ] [WebXR](https://github.com/immersive-web/webxr)
- [ ] [WebXR Gamepad Module](https://github.com/immersive-web/webxr-gamepads-module)
- [ ] [WebXR AR Module](https://github.com/immersive-web/webxr-ar-module)
- [ ] [Dom Overlays](https://github.com/immersive-web/dom-overlays)
- [ ] [Hit Test](https://github.com/immersive-web/hit-test)
- [ ] [AR Common](https://github.com/immersive-web/ar-common)

CG
- [ ] [Anchors](https://github.com/immersive-web/anchors)
- [ ] [Computer Vision](https://github.com/immersive-web/computer-vision)
- [ ] [Geo Alignment](https://github.com/immersive-web/geo-alignment)
- [ ] [Layers](https://github.com/immersive-web/layers)
- [ ] [Lighting Estimation](https://github.com/immersive-web/lighting-estimation)
- [ ] [Navigation](https://github.com/immersive-web/navigation)
- [ ] [Performance Improvements](https://github.com/immersive-web/performance-improvements)
- [ ] [Real World Geometry](https://github.com/immersive-web/real-world-geometry)
- [ ] [Spatial Favicons](https://github.com/immersive-web/spatial-favicons)
- [ ] [WebXR Hands Input](https://github.com/immersive-web/webxr-hands-input)

Others
- [x] [Administrivia](https://github.com/immersive-web/administrivia)
- [ ] [ImmersiveWebDev](https://github.com/immersive-web/immersiveweb.dev)
- [ ] [homepage]( https://github.com/immersive-web/homepage)
- [ ] [WebXR Samples](https://github.com/immersive-web/webxr-samples)
- [ ] [WebXR Inputs Profiles](https://github.com/immersive-web/webxr-input-profiles)
- [ ] [WebXR Polyfill](https://github.com/immersive-web/webxr-polyfill)
- [ ] [WebVR Polyfill](https://github.com/immersive-web/webvr-polyfill) 
- [ ] [Cardboard VR Display](https://github.com/immersive-web/cardboard-vr-display)
- [ ] [WebXR Test API](https://github.com/immersive-web/webxr-test-api)
- [ ] [Immersive Web Github.io](https://github.com/immersive-web/immersive-web.github.io)
- [ ] [WebVR Polyfill dpdb](https://github.com/immersive-web/webvr-polyfill-dpdb)
- [ ] [WebXR Reference](https://github.com/immersive-web/webxr-reference)(Archive?)
- [ ] [Privacy and Security](https://github.com/immersive-web/privacy-and-security)
- [ ] [WebVR Rocks](https://github.com/immersive-web/webvrrocks)
- [ ] [Proposals](https://github.com/immersive-web/proposals)
- [ ] [Community Resources](https://github.com/immersive-web/community-resources)(?)
- [ ] [WebVR](https://github.com/immersive-web/webvr)

**Comment by himorin** [comment]
note, I think most of these repositories uses gh-pages for source branch of github pages, but wait for our (W3C team)'s investigation on how to configure to use `main` branch as their source if `master` is source currently.

**Comment by Yonet** [comment]
@himorin thank you, I'll wait.

**Comment by himorin** [comment]
As for now:

- All WG repos use gh-pages for github pages, and master
- In CG, 
  - use gh-pages for github pages, and master: 'Anchors', 'Layers'
  - master is used, no github pages: 'Computer Vision', 'geo-alignment', 'lighting-estimation', 'navigation', 'performance-improvements', 'real-world-geometry', 'spatial-favicons', 'webxr-hands-input'
- In Others
  - master is used, no github pages: 'administrivia', 'privacy-and-security', 'proposals ', 'community-resources', 
  - master is used, and also for github pages: 'immersiveweb.dev', 'homepage', 'webxr-samples', 'webxr-polyfill', 'webvr-polyfill', 'cardboard-vr-display', 'immersive-web.github.io', 'webvr-polyfill-dpdb', 'webxr-reference', 'webvr'
  - use gh-pages for github pages, and master: 'webxr-input-profiles', 'webxr-test-api', 'webvrrocks', 

I think 'AR common' repo listed in WG is others (no github pages, not actively used)?

**Comment by Yonet** [comment]
@himorin is it ok to change the master branches in any of them. Would anything, like the IPR tool be affected by the change? If not, we can just rename the master branch to main and set it as default branch.

**Comment by himorin** [comment]
I believe [IPR tool](https://labs.w3.org/repo-manager/pr/open) picks PR notification, but not checking repositories directly. (also PR notification contains branch of PR source and target to merge) 
For ones with 'no github pages', I think we are fine to rename.
I'm not sure for ones with 'gh-pages for github pages', by mean of how external tool (like travis for generating gh-pages) works. For these, I think we'd better to wait verification by W3C team (@dontcallmedom, any further comment?).

**Comment by dontcallmedom** [comment]
as @himorin said, the IPR tool doesn't deal with branches directly, so we don't need to worry about it.

From our early investigation, there are 2 main challenges in renaming master to main:
* anybody who has a local clone of the repo will have to update their local config to point to the new upstream branch
* only master and gh-pages can be used as a source of github.io pages - so for any repo where master is directly the source of github.io, renaming it to main is not an option at the moment

Beyond these, there are additional checks to keep in mind:
* update any CI process that might refer to master explicitly (e.g. in travis.yml)
* update the branch protection rules that might have been set specifically for master

**Comment by himorin** [comment]
(for record. github provides notes: https://github.com/github/renaming )

**Comment by TrevorFSmith** [comment]
Please don't change the immersive-web-weekly repo over to `main`. I started out using that but GitHub depends on `master/docs/` to serve immersivewebweekly.com and there's currently no way to serve `main/docs/`, only a separate branch if there is no `master`.

Hopefully GitHub will eventually make it possible to serve a site from /docs/ from the default branch (no matter its name) but they're not there, yet.

**Comment by lazerwalker** [comment]
For what it's worth, it's possible/straight-forward to set up a minimal GitHub Action that deploys a given directory in the current branch to GitHub Pages. 

I suspect it's not worth adding that deployment complexity now rather than waiting for GH to finish their default branch migration work, but throwing out that I'm happy to contribute the time to get that infrastructure in place if it's desired.

**Comment by himorin** [comment]
hi, sorry that I've left this untouched for long.
github added a feature to choose a branch for github pages other than `gh-pages` or `master`, so I think we can go ahead for this point.
I suppose mass update at one time over all repository might be better for participants (not to make confusion between repositories), and also we need to take some time for announcement.
how do you all think?

**Comment by himorin** [comment]
finished all, and see no issue. closing this.
