### ISSUE TITLE
Set up a form for community members to submit news and links

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#110]

**Comment by TrevorFSmith** [comment]
@Yonet suggested that we could use Issues that auto-sort themselves into the [Immersive Web Weekly project](https://github.com/immersive-web/administrivia/projects/2) for transparency and source tracking.

**Comment by TrevorFSmith** [comment]
I think I'm going to close this as will-not-fix until we see how the Pull Request + email-trevor method works for folks who want to contribute links. If a GitHub login or emailing me seems to be a barrier then we can add a form.
