### ISSUE TITLE
Transfer the source repo to the IW GitHub org

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#111]

**Comment by jsantell** [comment]
I just made https://github.com/jsantell/immersive-web-weekly public; when transferring, I get ` You don’t have the permission to create public repositories on immersive-web` -- I think most of you have collaborator access to the repo by now, but not sure if that's sufficient to transfer it into the org. I can pass it to someone's personal account with org access, or I can try again if granted org access. Let me know and I can try again!

**Comment by TrevorFSmith** [comment]
I have created a [new repo](https://github.com/immersive-web/immersive-web-weekly) and will transfer code over.
Just to double check, @jsantell, it's OK with you if code from your immersive-web-weekly repo is copied to the (also MIT licensed) IW org repo?

**Comment by jsantell** [comment]
FYI I deployed the latest changes in IW/IWW repo to the site for now with updated verbiage

**Comment by TrevorFSmith** [comment]
@jsantell I believe that the DNS for immersivewebweekly.com is pointed at GitHub Pages hosting so the vhost shouldn't be receiving traffic.

**Comment by jsantell** [comment]
Ah, looks like it! A false positive is still a positive :+1:
