### ISSUE TITLE
Transfer immersivewebweekly.com domain registration to the same system as the other IWCG domains.

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#112]

**Comment by TrevorFSmith** [comment]
After discussing with the chairs, it turns out that domain ownership of the other domains isn't consolidated.

The plan is to to temporarily transfer immersivewebweekly.com to Transmutable's Route 53 account and then work toward consolidating them all into one place.

**Comment by jsantell** [comment]
Passed auth code along to @TrevorFSmith

**Comment by TrevorFSmith** [comment]
Transfer started. Waiting for the gears to grind, email links to be clicked, propagation, etc.
The new registrar (Route53) has a hosted zone that has the same A record for the domain pointing to Jordan's vhost which will stay in place until #113 is completed.

**Comment by TrevorFSmith** [comment]
Ok, it looks like the domain transfer is complete and propagation has started. There should be no visible change as it's still resolving to Jordan's vhost.
