### ISSUE TITLE
Set up hosting and publishing using GitHub Pages and Actions

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#113]

**Comment by TrevorFSmith** [comment]
I created a new [immersive-web-weekly repo](https://github.com/immersive-web/immersive-web-weekly) under the IW org and am looking at how to set it up.

**Comment by TrevorFSmith** [comment]
Ok, this came together pretty quickly!

I pulled over Jordan's system, moved around bits to work with GitHub Pages, removed some of the more complex parts of the site, and then pointed immersivewebweekly.com at the GitHub hosted pages. So, at this point we're no longer using Jordan's vhost!

**Comment by AdaRoseCannon** [comment]
Wow nice! Good work!
