### ISSUE TITLE
Update the privacy policy to reflect the IWCG's policies.

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#116]
https://immersivewebweekly.com/privacy/

**Comment by jsantell** [comment]
:wave: @Yonet 

Is there a source for IWCG's privacy policies? I can update this on the site until the host switch

**Comment by TrevorFSmith** [comment]
IANAL, of course:

Here are the W3C's general privacy policies for w3.org and email lists:
https://www.w3.org/Consortium/Legal/privacy-statement-20140324

The IWCG's Code of Coduct: https://github.com/immersive-web/community-resources/blob/master/CODE_OF_CONDUCT.md

For IWW I think we'll need to be a bit careful in the privacy statement to note that we use an email service (MailChimp).

Contributions submitted via GitHub Issues to the public IWW repo can, I think, be covered under the same license as the repo (MIT).

For other contribution channels (e.g. email to me, an online form) we'll have to be careful to note that nothing secret should be contributed and it all goes into the public domain.

**Comment by TrevorFSmith** [comment]
After further review of the existing policy document, I think it's probably OK for the IWW with just a few changes to note that it's managed by the IWCG and with a new contact email address. I will remove Google Tag Manager scripts from the site and email templates so we can remove that bit.
