### ISSUE TITLE
Cloud Anchor discussion at TPAC?

### ISSUE THREAD

**Issue by toji** [immersive-web/administrivia#126]
This was mentioned on this morning's editors call as something that has seen a fair amount of interest from users but which we don't have line-of-sight to a solution for. It may be productive to start a conversation on the topic at TPAC, and ideally we could convince some individuals with knowledge of how the current proprietary systems work engage with us as well. It's unlikely that we will be able to find any solutions at this point, but getting people thinking about it is worthwhile.

**Comment by Yonet** [comment]
Had discussion on [TPAC 2020](https://github.com/immersive-web/administrivia/tree/main/TPAC-2020) Day 5.
