### ISSUE TITLE
Home for Depth API proposal

### ISSUE THREAD

**Issue by bialpio** [immersive-web/administrivia#129]
Hi Immersive Web!

I'd like to start some work related to introducing Depth API to WebXR. The main question then is whether it should be a separate repository, or should it be included as a part of our existing repos (real-world-geometry comes to mind).

I've put my initial thoughts about the API in my personal, publicly visible repository, please take a look at the explainer in case that is something that could help with making a decision: https://github.com/bialpio/webxr-depth-api/blob/master/explainer.md.

So far it seemed that we tended to create new repository for each new feature. In this particular case, I do not see any problems with that approach as I do not think depth API will need to strongly depend on something from other repositories apart from WebXR Device API, but I'd still like to hear what people think.

**Comment by Yonet** [comment]
Created [depth-sensing repo](https://github.com/immersive-web/depth-sensing) and closing this issue. Thank you @bialpio.
