### ISSUE TITLE
build/move list of specs into one place

### ISSUE THREAD

**Issue by himorin** [immersive-web/administrivia#132]
from https://github.com/immersive-web/immersive-web.github.io/pull/5, for maintenability (and keeping consistency), I'd propose to build a list of specs and their related information into one place (at homepage?), and to replace existing lists with a link to there.

possible places to update (tentative list):

- [ ] [immersive-web.github.io README](https://github.com/immersive-web/immersive-web.github.io/blob/master/README.md), to be shown as https://immersive-web.github.io/
- [ ] modules list in spec README (ex. [webxr](https://github.com/immersive-web/webxr#specifications))
- [ ] [homepage README](https://github.com/immersive-web/homepage/blob/master/README.md)
- [ ] [homepage home](https://github.com/immersive-web/homepage/blob/master/index.html), to be shown as https://www.w3.org/immersive-web/ (possible target of listing)

also add link from:

- [ ] [immersiveweb.dev](https://github.com/immersive-web/immersiveweb.dev)

**Comment by himorin** [comment]
@Yonet  (wondering over some possibility,,, and) Considering long list of our full WG specs and CG incubations, how about to 

- have a dedicate page for full list of work targets, including their status, links (/TR, ED, issues, etc.), and related information (for our use) like transition CfCs or wide reviews
- add link to new page to homepage at the bottom of 'Drafts and Notes', as like 'See also full list of drafts and incubation' (keep list of 'Drafts and Notes' as WG specs)
- replace all lists with a link to new page

**Comment by Yonet** [comment]
@himorin great idea.

> have a dedicate page for full list of work targets, including their status, links (/TR, ED, issues, etc.), and related information (for our use) like transition CfCs or wide reviews

I will look into automating that page with links and issues. That would be the more maintainable solution. I wonder if there is such automation already through [RM](https://labs.w3.org/repo-manager/repos). Do you have any idea?
Thank you for the suggestion.

**Comment by himorin** [comment]
For repository manager, I assume (or AFAIK) there is no option to filter list of repositories by group, but better to ask @dontcallmedom .
The `w3c.json` file is used for repository manager etc., to tell which group is working on, so there could be possibility to build some tool to list repository per group. But I haven't heard on these yet....

**Comment by dontcallmedom** [comment]
We have an automatically maintained [list of repos associated to groups](https://w3c.github.io/validate-repos/report.json) which could be used to build this view.

A lot of it might already be in the relevant Chairs dashboards for the groups:
* WG: https://www.w3.org/PM/Groups/chairboard.html?gid=109735
* CG: https://www.w3.org/PM/Groups/chairboard.html?gid=87846

**Comment by AdaRoseCannon** [comment]
Omg I had no idea that existed!!

**Comment by himorin** [comment]
Ah, I haven't noticed about united json file as backend of chairs' tool. We might be possible to use that json file, and also additional self maintained data for our internal use if we want to add some (like status, and records).
@Yonet let me prototype some at somewhere offline from PR.

**Comment by himorin** [comment]
@Yonet first draft (not all info included into internal data yet)
https://himorin.github.io/immersive-web-homepage/list_spec.html

**Comment by Yonet** [comment]
@himorin thank you so much for doing this. Is there any way we can separate or emphasize what is WG vs CG?

**Comment by himorin** [comment]
also we may be possible to have this kind of list somewhere?: https://github.com/immersive-web/proposals/issues/34

**Comment by himorin** [comment]
> @himorin thank you so much for doing this. Is there any way we can separate or emphasize what is WG vs CG?

for this, updated by 600e16e (removed left nav, added h2 for each group)

**Comment by himorin** [comment]
Now we launch list_spec page at www.w3.org, so let me move on this issue. (will file PRs to repositories shortly.)

**Comment by himorin** [comment]
opened PRs to github.io, WG homepage, and webxr repository. please kindly check these. (I'd propagate to other spec repos once discussions on PR at webxr one finished and merged.)

**Comment by himorin** [comment]
closing, now we should have a link in relevant pages.
