### ISSUE TITLE
Home for AR image tracking proposal

### ISSUE THREAD

**Issue by klausw** [immersive-web/administrivia#135]
Hello immersive web,

I'm currently exploring ideas for a WebXR image tracking API based on driver-level detection that doesn't require application-side raw camera access. I've started on a draft explainer in my personal repository, https://github.com/klausw/webxr-image-tracking/blob/main/explainer.md , and would like to start discussions with the broader group.

What would be a good home for this? The computer-vision repository mentions this use case in https://github.com/immersive-web/computer-vision/blob/master/cv-in-browser.md, but my impression was that this was assumed to be a component of a more general CV framework which we don't have yet.

Would there be interest in a smaller-scope feature (and separate repository) for this specific use case? This shouldn't preclude having a more general CV API in the future.

**Comment by klausw** [comment]
@grorg FYI. The initial agenda topic is mainly intended to discuss next steps for moving forward with the proposal, not necessarily discussing API details, but it would be good if you could join the meeting if you're interested in this area., I've tried to keep ARKit features in mind while working on the draft explainer, but since I don't have direct experience with that I was limited to public documentation.

**Comment by AdaRoseCannon** [comment]
@klausw would you like to introduce this at TPAC on a call, to go through it and raise awareness?

**Comment by klausw** [comment]
Sure, I think we also have some related topics for AR features that would be worth discussing, i.e. raw camera access. Bigger picture, I think it would be good to follow up on world understanding / computer vision in general.

**Comment by klausw** [comment]
The initial draft explainer now lives at https://github.com/immersive-web/marker-tracking/blob/main/explainer.md , thanks @AdaRoseCannon for setting up the repo. As discussed in Monday's meeting, we should look into generalizing it for different types of markers as a followup.
