### ISSUE TITLE
2021 Web Almanac article for WebXR

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#150]
We might want to add WebXR to httparchive. Issue is to remind us to discuss.
https://almanac.httparchive.org/en/2020/

**Comment by Yonet** [comment]
Guide here: https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors%27-Guide

**Comment by Yonet** [comment]
/agenda to see if anyone is interested in working on HTTP Archive.

**Comment by saitogroup** [comment]
+1

**Comment by Yonet** [comment]
@saitogroup here are [some of the issues](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) but we can use your help on WebXR stuff too. Thank you for volunteering.

**Comment by Yonet** [comment]
@TrevorFSmith, and would you fill this [contributor form](https://docs.google.com/forms/d/e/1FAIpQLSeZJhAvmSTFtQpahplL7uwdBo7UB1iAkRp2MUaPK74KsrN1fQ/viewform) when you have a chance. Thanks 🥇

**Comment by TrevorFSmith** [comment]
> @TrevorFSmith, and would you fill this contributor form when you have a chance. 

Submitted!

**Comment by TrevorFSmith** [comment]
@Yonet I'm assuming that the Web Almanac organizers will reach out to us now that we've filled out their form but let me know if there's something else we should do in the meantime. One of my to-do items is to become more familiar with the latest almanac.

**Comment by Yonet** [comment]
@TrevorFSmith will do. You might also get a github notification if they add you in the org. I'll keep an eye.

**Comment by TrevorFSmith** [comment]
I added a comment (https://github.com/HTTPArchive/almanac.httparchive.org/issues/2167#issuecomment-828563763) to the Issue that the almanac organizer is using to plan the work.

**Comment by Yonet** [comment]
@Delta-Ark looks like Media section need more help other than the WebXR section. If you are interested, please comment on  [HTTPArchive/almanac.httparchive.org#2167 (comment)](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2167#issuecomment-828563763).

**Comment by Yonet** [comment]
Closing this issue, follow the work on [here](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2144)
