### ISSUE TITLE
Move Depth Sensing to WG

### ISSUE THREAD

**Issue by bialpio** [immersive-web/administrivia#153]
Now that we have an implementation of Depth Sensing API ready in Chrome for Android (behind a flag for now, getting ready to be shipped), it's probably time to move the API into WG.

**Comment by himorin** [comment]
propose to close, [concluded at 18/March](https://lists.w3.org/Archives/Public/public-immersive-web-wg/2021Mar/0013.html), and changed by https://github.com/immersive-web/depth-sensing/pull/22

**Comment by himorin** [comment]
@AdaRoseCannon propose to close, [concluded at 18/March](https://lists.w3.org/Archives/Public/public-immersive-web-wg/2021Mar/0013.html), and changed by https://github.com/immersive-web/depth-sensing/pull/22

**Comment by AdaRoseCannon** [comment]
Thanks @himorin yep this looks complete i'll close it
