### ISSUE TITLE
Home for Raw Camera Access proposal / repository

### ISSUE THREAD

**Issue by bialpio** [immersive-web/administrivia#154]
Hey all,

I'm looking into reviving the raw camera access API and I was wondering what would be the best way for me to proceed here.

Current state of things:
- I have a [personal repository](https://github.com/bialpio/webxr-raw-camera-access) with an early draft of the API that is what we have currently implemented in Chrome for Android behind a flag.
- There is an Immersive Web's [Computer Vision](https://github.com/immersive-web/computer-vision) repo which at the first glimpse seems to be the best fit for this proposal, but I do not think there was any activity on it for the past couple of months.

I'd like to propose creating a new repository for the raw camera access API. New repository is probably best here since it's a bit tricky to manage repositories that have multiple co-located spec drafts (#152 has a bit of context on that). I do not foresee that the API would depend on any other modules except the core spec.

Let me know if you think there's a better way to make progress here!

**Comment by AdaRoseCannon** [comment]
I vaguely remember there being discussion that raw camera access might not
be a great idea since it is so powerful and perhaps focussing on providing
the solutions to the problems which developers want raw camera access to
solve would be a better path.

I can still make a repo if you want though but first it might be worth
making sure that other implementators also want to take this path too. Let
me know how you want me to proceed.

**Comment by bialpio** [comment]
This makes sense - we have been receiving requests for raw camera access API and were postponing working on it mostly due to privacy concerns, but the other side of the argument is that raw camera access allows for more rapid prototyping of solutions while UA vendors work on standardizing privacy-preserving APIs. This was also something that was mentioned during yesterday's call in the context of marker tracking API - I believe 8th Wall would be interested in experimenting with JS-powered marker tracking from within WebXR. There are also use cases that are only possible with raw camera access (and there may be more use cases that we don't even know we should be solving). I think Computer Vision is where those discussions & API incubations were supposed to happen so it'd seem to me that there was already a need for such features - creating a new repository would only help with the organizational aspect of the work.

For now I should be able to proceed in my private repository, but I'm mostly worried that folks will be hesitant to participate due to IP concerns. @-ing people who may have some opinion on this as well: @klausw, @nbutko, @thetuvix.

/agenda In case we still do not have a clear way forward by the time of the next meeting.

**Comment by bialpio** [comment]
Thanks for creating the repository! I think I may need some assistance in order to transfer the issue from one repo to another, as I seem to be unable to do so myself. The issue I'd like to move is bialpio/webxr-raw-camera-access#1 - I've tried using the "Transfer issue" option but I'm unable to select the immersive-web/raw-camera-access repo as the destination despite the fact that I have admin rights to that repository. Did anyone run into something like this before? Are there any tools I could use to move the discussion cleanly? There's always an option of copy-pasting the comments to the new spot but if there's a better way, I'd prefer to try it first.

**Comment by himorin** [comment]
I don't think it's possible to transfer issue from one mentioned to immersive-web one.
https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository
> You can only transfer issues between repositories owned by the same user or organization account.

**Comment by bialpio** [comment]
Closing this issue, the repo for raw camera access is created (with all the relevant content moved), and I decided to create a new issue that links to the original thread from the old repo, so no need to migrate anything anymore.
