### ISSUE TITLE
Solve a11y 4eva

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/administrivia#157]
We need to help Brandon write the a11y doc. There is lots of context spread around that needs to be gathered together. This will be a group drafting activity to bring a document mostly together. 

Document link to come later probably a publicly editable  Google Doc or hackmd or something.

/agenda this needs to be an entire meeting activity

**Comment by AdaRoseCannon** [comment]
This is important and high priority because it is blocking CR.

**Comment by DrX3D** [comment]
I can help here as long as it is not w/o June 7. It aligns with work being conducted by Khronos.

**Comment by Yonet** [comment]
@DrX3D we have a draft of the [document](https://docs.google.com/document/d/1U-SuIGtQtqobdOyoc218CnJKqxuoimhpIGjGyx7fQg4/edit?usp=sharing) if you would like to add to it. Thanks!

**Comment by himorin** [comment]
@AdaRoseCannon close this??

**Comment by AdaRoseCannon** [comment]
Okay :)
