### ISSUE TITLE
Configure branch protection rules on immersive-web repositories

### ISSUE THREAD

**Issue by himorin** [immersive-web/administrivia#158]
There is a some chance of mis-operation of git command to commit directly to the default branch which will be a direct update of output, such as spec or web page. 
(e.g. https://github.com/immersive-web/immersiveweb.dev/issues/58)
We might be better to configure branch protection rules on immersive-web repositories, to prohibit direct commit without PR.

**Comment by AdaRoseCannon** [comment]
If @cabanier @toji and @Manishearth are fine with it and give their approval here then it is probably okay to go ahead and do that without much further discussion. If someone else in the groups take issue we can start a discussion in a call but it doesn't seem controversial to me.

**Comment by cabanier** [comment]
+1 for me

**Comment by Manishearth** [comment]
+1

**Comment by toji** [comment]
+1

**Comment by himorin** [comment]
We might have another editor(s) in specs, but it seems we can go forward on this addition of branch protection rules.
@AdaRoseCannon do we want to have in IWCG ones also? And, any non spec repos want to have this (e.g. immersive-web.dev)?

**Comment by AdaRoseCannon** [comment]
I think it's okay to do it globally and see how it goes. I don't think it should change too many people's work flows. I'm off work for a couple of weeks so I may not be able to respond to messages super quickly.

**Comment by himorin** [comment]
ok. Let me configure branch protection rule(s) on the default branch (currently set to `main`), and welcome comments from groups.

**Comment by himorin** [comment]
configured branch protection to `main` branch (without any option enabled, e.g. require PR before merging) over all repositories except for this `administrivia` one. If this does not work on preventing direct push to the `main` branch, it seems we [need to enable `require PR before merging` option](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)...
Note, chairs has owner status in this organization, so counted as `administrator` - so tests and/or comments are quite welcome from non-chairs...

**Comment by himorin** [comment]
closing, we should have working branch protection now.
