### ISSUE TITLE
Group meeting planning for TPAC 2021

### ISSUE THREAD

**Issue by himorin** [immersive-web/administrivia#161]
We need to decide whether to have group and joint group calls during TPAC group meeting week. Also for joint group meeting, we need to coordinate with external groups, if any idea exists.
https://www.w3.org/wiki/TPAC/2021/GroupMeetings

Also there is possibility to [provide recorded video(s) to TPAC](https://www.w3.org/wiki/TPAC2021/Demos_and_Group_updates) website from WG. Need to show interest by Sep/15, and to provide recorded viewo(s) by Sep/27.

**Comment by AdaRoseCannon** [comment]
Yes! This is a good thing to cover! We're also going to discuss it at today's chair's meeting

**Comment by AdaRoseCannon** [comment]
[Planning Doc](https://docs.google.com/document/d/1PLez9igpQFuVy2kXuNw4kkMMqCmBqgc2ayONK60fNcs/edit#)

We will build this document up  during the meeting. People are welcome to contribute beforehand.

**Comment by Yonet** [comment]
[TPAA Agenda](https://github.com/immersive-web/administrivia/tree/main/TPAC-2021#readme)
