### ISSUE TITLE
Successes! What cool things have had a Working Draft published since last time?

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/administrivia#165]
This is just for a short topic to do a victory lap of all the wonderful things which have happened since the last TPAC.

**Comment by Yonet** [comment]
Maybe we can do this for face-to-face @AdaRoseCannon

**Comment by AdaRoseCannon** [comment]
Great idea!

/facatoface

**Comment by AdaRoseCannon** [comment]
Great idea!

/facetoface

**Comment by Yonet** [comment]
Thank you for the presentation @AdaRoseCannon, I'm  closing the issue.
