### ISSUE TITLE
Charter progress update and Charter 3:The Chartering

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/administrivia#166]
/tpac Charter finishes next year did we meet our expectations?
What do we want the new charter to be?

**Comment by AdaRoseCannon** [comment]
Add to charter:
* Model Viewer Tag

**Comment by AdaRoseCannon** [comment]
/agenda to discuss https://github.com/w3c/immersive-web-wg-charter/issues/39

**Comment by himorin** [comment]
@AdaRoseCannon @Yonet  close this? we have rechartered.

**Comment by AdaRoseCannon** [comment]
Thanks!
