### ISSUE TITLE
TPAC 2021 action items summary

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#171]

**Comment by AdaRoseCannon** [comment]
Great idea doing it here. I started making notes of charter changes here: https://github.com/immersive-web/administrivia/issues/166

**Comment by Yonet** [comment]
[Action items from TPAC](https://docs.google.com/document/d/1WAZAmA7TGi_2QAR6o_jr8hOPM7ybzrKUt80tAajzyhg/edit?usp=sharing)
