### ISSUE TITLE
Set up next FTF post-TPAC.

### ISSUE THREAD

**Issue by cwilso** [immersive-web/administrivia#18]
Current suggestion:  San Jose, Jan 28-29th.

**Comment by ddorwin** [comment]
Keep in mind that Monday (28th) morning means people may have to travel on the weekend.

**Comment by cwilso** [comment]
Indeed, in reviewing my notes, we said 29-30.

**Comment by AdaRoseCannon** [comment]
Auditorium is booked at Samsung Research America from Tuesday January 29th through Wednesday January 30th from 8 a.m. to 6 p.m. Thank you Damon!!
