### ISSUE TITLE
TPAC 2022 Planning

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#180]
TPAC is scheduled for the week of September 12 - 16, 2022. The Venue is in Vancouver, B.C., Canada.
Hybrid meeting. 
Health Rules: https://github.com/w3c/TPAC2022-Health-rules

**Comment by himorin** [comment]
@Yonet close this? TPAC 2022 finished.

**Comment by AdaRoseCannon** [comment]
Thank you!
