### ISSUE TITLE
change editors' affiliation from Facebook to Meta

### ISSUE THREAD

**Issue by himorin** [immersive-web/administrivia#186]
Registration at W3C membership changed ([e.g. at list of participants page](https://www.w3.org/groups/wg/immersive-web/participants?sortaff=1)), do we need/want to change also in editors' list?

/cc @AdaRoseCannon @cwervo @Yonet

**Comment by Yonet** [comment]
That would make sense @himorin himorin.

**Comment by himorin** [comment]
closing this. all PRs merged.
