### ISSUE TITLE
Request TAG review of WebXR (post-FPWD).

### ISSUE THREAD

**Issue by cwilso** [immersive-web/administrivia#19]

**Comment by AdaRoseCannon** [comment]
Should we do this now?

**Comment by NellWaliczek** [comment]
Now that the gamepad stuff is merged... I think the last major issues before requesting TAG review are getting the hit-test apis into the spec and probably the ones relating to the `requestReferenceSpace()` signature.  Once that's done I think we can call for TAG review. @toji what do you think?
