### ISSUE TITLE
Establish logos

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/administrivia#2]
Both for WebXR and the Immersive Web
Hire a designer
Set up voting for the community

**Comment by cwilso** [comment]
I pinged internally, and I think we may have some design resources available.

**Comment by koalie** [comment]
If at all possible, I'd like if the logo could leverage the W3C Blue:
  #005A9C | R=0, G=90, B=156

That would be one easy way to tie to W3C, considering how difficult it is to leverage the W3C icon in logos.
