### ISSUE TITLE
Tag F2F issues

### ISSUE THREAD

**Issue by Yonet** [immersive-web/administrivia#205]
Please tag the issues you would like to discuss on F2F meeting.
Feel free to create new issues and don't forget to rsvp. 

/agenda

**Comment by trusktr** [comment]
I would like to make some friends in person.

/rsvp

**Comment by nbutko** [comment]
If possible I'd like to give a short talk in a 15 minute timeslot (it seems like there are a couple of these open). Is it possible to add to the agenda?

**Comment by AdaRoseCannon** [comment]
@nbutko Marking agenda items has now closed but we can find a slot on the day, please remind me in the morning.

**Comment by AdaRoseCannon** [comment]
Closing this thread since it's purpose was to remind us to remind people to tag their issues for the face to face
