### ISSUE TITLE
Unconference topics for TPAC - add them here

### ISSUE THREAD

**Issue by cwilso** [immersive-web/administrivia#24]

**Comment by AdaRoseCannon** [comment]
Session options: immersive

Discussion around https://github.com/immersive-web/webxr/issues/388

**Comment by NellWaliczek** [comment]
Boaz from Bocoup wanted to discuss testing of/for XR

**Comment by blairmacintyre** [comment]
sharing maps and anchors

**Comment by blairmacintyre** [comment]
minimal AR mode

**Comment by grassel** [comment]
topic proposal: **shareable anchors** also known as cloud anchors (Guido Grassel)
how to share anchors from one browser to another / social WebXR apps
how to persist an anchor for use in the same browser later.

**Comment by NellWaliczek** [comment]
Bikeshedding https://github.com/immersive-web/webxr/issues/418
