### ISSUE TITLE
Which AR features are planed in the upcoming API spec?

### ISSUE THREAD

**Issue by D33pTh0ught** [immersive-web/administrivia#47]
Apologies in advance if this is not the right place to ask.
As I understand the focus of this draft is to reach feature parity with the previous webVR API. I was wondering about which AR features are going to ship in this release since, as I understood it, even features that were usable in previous versions like hit-test are still discussed as proposals.
Are AR features like hit-test or anchors included in the upcoming specs and do the proposed anchors also include image targets?

Kind regards

**Comment by AdaRoseCannon** [comment]
This is going to be discussed at the upcoming face-to-face meeting.

**Comment by cwilso** [comment]
Note https://github.com/immersive-web/administrivia/blob/master/modules.md; that's where this will be codified.
