### ISSUE TITLE
Create a PR for the proposals README that fleshes out the rest of the process of moving from idea into active CG repo

### ISSUE THREAD

**Issue by TrevorFSmith** [immersive-web/administrivia#6]
Rough idea:

Gates for moving spec into WG:
- Proposal Issue
- Three implementer +1s
- Create repo and stabilize IDL
- Review by WG and react to feedback
- Chairs of the appropriate WG agree to take it on

**Comment by cwilso** [comment]
- connect to WGs to get them to take it on.

**Comment by TrevorFSmith** [comment]
Helpful reference: https://github.com/WICG/admin/blob/gh-pages/README.md
