### ISSUE TITLE
Demos at TPAC F2F

### ISSUE THREAD

**Issue by ldao** [immersive-web/administrivia#61]
As per our discussion on the WG call today, I'm creating an issue so that we can schedule demos during the WG F2F at TPAC and also see what we could offer to Coralie at W3C. I'm there Mon - Wed and would be happy to help organize this part.

**Comment by AdaRoseCannon** [comment]
How long do you need to demo?

Is it something which can be shared on the screen whilst it is being used?

**Comment by AdaRoseCannon** [comment]
/facetoface addnig the face to face tag

**Comment by ldao** [comment]
I have some webVR projects that I could show on screen for the whole group.
I'm seeing what I can get working on the Oculus Go and Quest and will test casting from the device.
Will confirm that by Thursday but if I remember from other F2F's I should keep it under 20-30mins and the we can have the full ones at the W3C table?
Will anyone have a full nVidia 1080+, Rift/Rift S setup there? We also have 6DOF VR projects created in Unity that might be good for reference.

**Comment by ldao** [comment]
I looked at the schedule and I won’t be able to stay for the demos because I’m flying out Wed at 6pm but I can load ours up if anyone is able to. I’m seeing Kip tomorrow and will see what he’s thinking.

**Comment by ldao** [comment]
I’m in Fukuoka. Let me know what day you’re thinking so I can do a quick tech test in the am or at lunch.

**Comment by AdaRoseCannon** [comment]
Our demos are currently on Monday:

https://github.com/immersive-web/administrivia/blob/master/TPAC-2019/README.md
