### ISSUE TITLE
Remove the WebXR Reference repo

### ISSUE THREAD

**Issue by jpmedley** [immersive-web/administrivia#83]
https://github.com/immersive-web/webxr-reference

Now that the API has started to ship in browsers, long-term the developer-facing content should be [the MDN content](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API). The Repo in this working group can only ever be distracting and out of date.

It looks like I have the authority to delete this repo. I'm opening this ticket so that link to it may be removed or changed to MDN.

**Comment by jpmedley** [comment]
@cwilso

**Comment by AdaRoseCannon** [comment]
@jpmedley sorry for the slow reply, you may delete it or update it to point to MDN, however you see fit, thank you for working on the WebXR reference content.

**Comment by himorin** [comment]
closing, target repository is already removed.
