### ISSUE TITLE
Move hit-testing and dom-overlay to WG

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/administrivia#91]
These are pretty stable should probably be moved across to make a standard, this issue is to keep track of that.

**Comment by AdaRoseCannon** [comment]
Done

**Comment by himorin** [comment]
@AdaRoseCannon should we remove incubation label from two repositories?

**Comment by AdaRoseCannon** [comment]
Yes, we also need a place to list which repos are in the Working Group now there are quite a few.

**Comment by himorin** [comment]
will (push a PR to) add to the site shortly for two.
have we decided to move others already? (I suppose not yet specifically in WG call etc., but should be agreed that current charter is approved in WG?)

**Comment by AdaRoseCannon** [comment]
There was a call a few weeks back where it was agreed upon to move them
into the WG (although I maybe misremembering @cwilso?)

**Comment by AdaRoseCannon** [comment]
I also just opened a PR in immersive-web/webxr to add them to the readme

**Comment by himorin** [comment]
I thought that was for two in this issue ( https://www.w3.org/2020/04/28-immersive-web-minutes.html#item01 )

ahh,, sorry that I've made you confused.. I meant others as added ones to new charter except for two referenced in this issue, like lighting-estimation or hand-input.

**Comment by himorin** [comment]
Do we need to have CONTRIBUTING.md and CODE_OF_CONDUCT.md as copy from template to these repos? or point to somewhere in README or something?

**Comment by AdaRoseCannon** [comment]
Pointing to the ones in immersive-web/webxr should be sufficient, I've been
using that as the core repository for the WG.

Ada

**Comment by himorin** [comment]
Thank you for comment.
I've checked existing ones (e.g. webxr, webxr-*-modules), and there seems some missing items like travis icon. Also some sections, like take part (incl. link to CoC in homepage repo) or relevant links, so let me push PRs to follow these format. (also, domoverlay states in incubation status with a link to proposals repository, still now...).

**Comment by himorin** [comment]
removed label 'incubation', and added PRs to repositories for updating README as following webxr one.
let me close this issue once these have merged

https://github.com/immersive-web/hit-test/pull/90
https://github.com/immersive-web/dom-overlays/pull/34

**Comment by himorin** [comment]
closing this, both PRs merged.
